### ISSUE TITLE
(AI) Summarise text in a document uploaded by a user

### ISSUE THREAD

**Issue by Ivy-leet** [COS301-SE-2022/Twitter-Summariser#698]
The acceptable formats are *.txt, *.pdf, *.doc, *.docx

**Comment by Zenthon** [comment]
It's already done

**Comment by Ivy-leet** [comment]
It isn't, please read title and description again. What's done is text from a textbox and not a document uploaded by a user.

**Comment by Zenthon** [comment]
But that is frontend's job to send the text. All the module does is receive text and process it
